apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monai-inference.fullname" . }}-backend-env
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: backend
    {{ include "monai-inference.labels" . | nindent 4 }}
data:
  CKPT_PATH:        {{ .Values.backend.env.CKPT_PATH | quote }}
  VAL_LOADER_PATH:  {{ .Values.backend.env.VAL_LOADER_PATH | quote }}
  TEMP_DIR:         {{ .Values.backend.env.TEMP_DIR | quote }}
  AMP_ENABLED:      {{ .Values.backend.env.AMP_ENABLED | quote }}
